#!/usr/bin/env python
# -*- coding: utf-8 -*-

import re, math, time, ConfigParser
from os import path, listdir, makedirs, system, remove
from BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer
from urllib import unquote
from datetime import datetime, tzinfo, timedelta
from shutil import copyfile
from distutils.sysconfig import get_python_lib
from jinja2.loaders import FileSystemLoader
from jinja2 import Environment
from werkzeug import script
from markdown import markdown

class Config:
    def __init__(self):
        self.is_parsed = False
        self._parser = ConfigParser.RawConfigParser(allow_no_value=True)
        rc_path = path.expanduser('~/.microrc')
        if path.exists(rc_path):
            self._parser.read(rc_path)
            self.is_parsed = True
        
    def __getattr__(self, option):
        if self.is_parsed:
            list = {
                'month': 'locale',
                'days': 'locale',
                'public': 'storage',
                'templates': 'storage',
                'pages': 'storage',
                'posts': 'storage',
                'to': 'sync'
            }
            if option in ['templates', 'pages', 'posts', 'public', 'build']:
                return path.expanduser(self._parser.get('storage', option))
            elif option == 'exclude_category':
                try:
                    return self._parser.get('system', option).split(',')
                except ConfigParser.NoOptionError:
                    return []
            elif option == 'post_per_page':
                return int(self._parser.get('system', option))
            elif list.has_key(option):
                return self._parser.get(list[option], option).decode('utf-8')
            else:
                return self._parser.get('system', option)

config = Config()

if config.is_parsed:
    BLOG_PATH = path.join(config.build, "blog")
    CATEGORIES = path.join(BLOG_PATH, "categories")
    ARCHIVES = path.join(BLOG_PATH, "archives")

class Entry:
    def __init__(self, *initial_data, **kwargs):
        for dictionary in initial_data:
            for key in dictionary:
                setattr(self, key, dictionary[key])
        for key in kwargs:
            setattr(self, key, kwargs[key])

class Category(Entry):
    pass

class TZ(tzinfo):
    def utcoffset(self, dt): 
        return timedelta(minutes=int(config.timezone_offset))
    
class Date(Entry):
    def get_full(self):
        locale_month = config.month.split(',')
        weekdays = config.days.split(',')
        day = int(self.day)
        month = int(self.month) - 1
        weekday = weekdays[self.get_datetime().weekday()]
        return weekday + ', ' + str(day) + ' ' + locale_month[month] + ' ' + str(self.year)

    def get_half(self):
        locale_month = config.month.split(',')
        weekdays = config.days.split(',')
        day = int(self.day)
        month = int(self.month) - 1
        weekday = weekdays[self.get_datetime().weekday()]
        return weekday + ', ' + str(day) + ' ' + locale_month[month]

    def get_iso(self):
        return self.get_datetime().isoformat()

    def get_datetime(self):
        return datetime(
            int(self.year), int(self.month), int(self.day), int(self.minute), int(self.second), 
            tzinfo=TZ()
        )

class Post(Entry):
    def get_full(self):
        return self.content + self.description

    def get_url(self):
        return 'http://' + config.host + '/blog/' + self.date.year + '/' + self.date.month + '/' + self.date.day + '/' + \
            self.name + '/'

    def has_excluded_cats(self):
        for category in self.categories:
            if category.name in config.exclude_category:
                return True;
        return False;

class Page(Entry):
    pass

class Press:
    def generate(self):
        self.load()
        self.load_first_press()
        print "Parsing done ..."
        self.gen_articles()
        print "Generation done ..."
        self.gen_pages()
        self.gen_categories()
        self.gen_archives()
        self.gen_feed()
        self.gen_subfeeds()
        self.gen_static()

    def load_first_press(self):
        year = datetime.now().year;
        for post in self.posts:
            if int(post.date.year) < year:
                year = post.date.year
        self.first_press = year

    def gen_articles(self):
        for post in self.posts:
            post_path = path.join(BLOG_PATH, post.date.year, post.date.month, post.date.day, post.name)
            rendered = self.render('article.html', post=post)
            self.write(post_path, rendered)

    def gen_pages(self):
        posts_filtered = []
        for post in self.posts:
            if post.has_excluded_cats():
                continue
            posts_filtered.append(post)
        size = len(posts_filtered)
        pages = math.ceil(float(size)/config.post_per_page) if size > config.post_per_page else 1
        i = 1
        while i <= pages:
            offset = i*config.post_per_page - config.post_per_page
            posts = posts_filtered[offset:offset+config.post_per_page]
            rendered = self.render('index.html', posts=posts, page=i, total_pages=pages)
            to = config.build if i == 1 else path.join(BLOG_PATH, 'page', str(i))
            self.write(to, rendered)
            i += 1

    def gen_categories(self):
        categories = self.sort_by_categories(self.posts)
        for key, value in categories.iteritems():
            category_path = path.join(CATEGORIES, key.lower())
            rendered = self.render('categories.html', years=self.sort_by_years(value), categories=key)
            self.write(category_path, rendered)

    def gen_archives(self):
        rendered = self.render('categories.html', years=self.sort_by_years(self.posts, True))
        self.write(ARCHIVES, rendered)

    def gen_feed(self):
        posts_filtered = []
        for post in self.posts:
            if post.has_excluded_cats():
                continue
            posts_filtered.append(post)
        rendered = self.render('atom.xml', posts=posts_filtered[0:30], )
        self.write(config.build, rendered, 'atom.xml')

    def gen_subfeeds(self):
        feeds = self.sort_by_feeds(self.posts)
        for key, value in feeds.iteritems():
            category_path = path.join(CATEGORIES, key.link.lower())
            rendered = self.render('atom.xml', posts=value, category=key)
            self.write(category_path, rendered, 'atom.xml')

    def gen_static(self):
        for page in self.pages:
            rendered = self.render('page.html', page=page)
            self.write(path.join(config.build, page.name), rendered)

    def render(self, template, **kwargs):
        template = self.get_base_template(template)
        options = {
            'host': config.host,
            'name': config.name,
            'author': config.author,
            'date': "%s&mdash;%s" % (self.first_press, datetime.now().year),
            'pages': self.pages,
            'datetime_now': datetime.now().replace(tzinfo = TZ(), microsecond = 0)
        }
        return template.render(dict(kwargs.items() + options.items()))

    def write(self, to, rendered, additional = 'index.html'):
        if not to.endswith('/'):
            to = to + '/'
        if not path.exists(path.dirname(to)):
            makedirs(path.dirname(to))
        with open(path.join(to, additional), "w") as file:
            file.write(rendered.encode('utf-8'))

    def get_base_template(self, name):
        template = Environment(loader=FileSystemLoader(config.templates))
        return template.get_template(name)

    def sort_by_years(self, posts, archive=False):
        years = {}
        include = {}
        if archive:
            for post in posts:
                if not (post.has_excluded_cats()):
                    include[post.date.year] = True
        for post in posts:
            if not archive or post.date.year in include:
                if not years.has_key(post.date.year):
                    years[post.date.year] = []
                if archive and (post.has_excluded_cats()):
                    pass
                else:
                    years[post.date.year].append(post)
        return reversed(sorted(years.iteritems()))

    def sort_by_categories(self, posts):
        categories = {}
        for post in posts:
            for category in post.categories:
                if not categories.has_key(category.link):
                    categories[category.link] = []
                categories[category.link].append(post)
        return categories
    
    def sort_by_feeds(self, posts):
        feeds = {}
        for post in posts:
            if not feeds.has_key(post.categories[0]):
                feeds[post.categories[0]] = []
            feeds[post.categories[0]].append(post)
        return feeds

class Octopress(Press):
    def load(self):
        self.posts = [self.parse_post(f) for f in reversed(listdir(config.posts))
            if path.isfile(path.join(config.posts, f)) and not f.startswith('.')
        ]
        self.pages = [self.parse_page(f) for f in reversed(listdir(config.pages))
            if path.isfile(path.join(config.pages, f)) and not f.startswith('.')
        ]

    def parse_post(self, name):
        f = file(path.join(config.posts, name), "r")
        post = f.read().decode('utf-8')

        list = post.split('---')
        settings = list.pop(1)
        body = "".join(list)

        body_list = body.split('<!-- more -->')
        content = body_list.pop(0)
        description = "".join(body_list)

        time=re.search('(?<=time:).+', settings)
        if time:
            time = time.group(0).strip().split(':')

        categories = re.search('(?<=categories:).+', settings).group(0).strip()
        categoriesList = categories.split(',') if (',' in categories) else categories.split()

        for key, item in enumerate(categoriesList):
            categoryLink = categoryName = item.strip()
            if ('/' in item):
                splitted = item.split("/", 1)
                categoryLink = splitted[1].strip()
                categoryName = splitted[0].strip()
            categoriesList[key] = Category(link=categoryLink, name=categoryName)

        link = re.search('(?<=link:).+', settings)
        if link:
            link = link.group(0).strip()

        date = Date(
            config=config,
            year=name[:4], 
            month=name[5:7], 
            day=name[8:10],
            minute=time[0] if time else 0,
            second=time[1] if time else 0
        )

        return Post(
            config=config,
            date= date,
            name=name[11:-9],
            title=re.search('(?<=title:).+', settings).group(0).strip()[1:-1],
            content=markdown(content, ['extra']),
            description=markdown(description, ['extra']),
            categories=categoriesList,
            link=link
        )

    def parse_page(self, name):
        f = file(path.join(config.pages, name), "r")
        page = f.read().decode('utf-8')
        list = page.split('---')
        settings = list.pop(1)
        body = "".join(list)
        return Page(
            name=name[:-9],
            title=re.search('(?<=title:).+', settings).group(0).strip()[1:-1],
            content=markdown(body, ['extra'])
        )

class Server(BaseHTTPRequestHandler):
    def do_GET(self):
        try:
            if self.path[-1:] == '/':
                self.path = self.path + 'index.html'
            f = open(config.build + unquote(self.path))
            self.send_response(200)
            self.end_headers()
            self.wfile.write(f.read())
            f.close()
            return
        except IOError:
            self.send_error(404, 'File not found')

def action_sync():
    system("rsync -avrz %s %s" % (config.build + "/*", config.to))
    print('Sync done ...')

def action_preview():
    server_address = ('127.0.0.1', 8080)
    httpd = HTTPServer(server_address, Server)
    print('Http server is running on http://127.0.0.1:8080')
    httpd.serve_forever()

def action_generate():
    engine = Octopress()
    system("cp -r " + config.public + "/* " + config.build )
    engine.generate()

def action_gp():
    action_generate()
    action_preview()

def action_gs():
    action_generate()
    action_sync()

def action_add(name=('n', '')):
    post_dst = config.posts + time.strftime("%Y-%m-%d") + '-' + name + '.markdown'
    copyfile(config.templates + 'base.markdown', post_dst)
    system("vim " + post_dst)

def action_rm(name=('r', '')):
    remove(config.posts + time.strftime("%Y-%m-%d") + '-' + name + '.markdown')

def action_commit():
    system("cd " + config.posts + "; git add . ; git commit -m 'up'; git push;")

def action_init():
    init_path = path.expanduser('~') + '/Documents/Micropress/'
    if not path.exists(init_path):
        makedirs(init_path, 0755)
    from_path = get_python_lib() + '/micropress/init/'
    system("cp -r " + from_path + " " + init_path )
    system("rm " + init_path + "/rctemplate")
    if not path.exists(path.expanduser('~/.microrc')):
        copyfile(from_path + 'rctemplate', path.expanduser('~/.microrc'))
        print('Config successfully saved in ~/.microrc')

if __name__ == '__main__':
    script.run()
